openapi: 3.0.0
info:
  title: Menu Planner
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /recipe:
    get:
      summary: Your GET endpoint
      tags:
        - recipes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  yield:
                    type: string
                  ingredients:
                    type: array
                    items:
                      $ref: '#/components/schemas/Ingredient'
            application/xml:
              schema:
                type: object
                properties: {}
      operationId: get-recipe
      description: Returns list of all recipes.
    parameters: []
    post:
      summary: ''
      operationId: post-recipe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
      tags:
        - recipes
      description: Create a new recipe.
components:
  schemas:
    Recipe:
      title: Recipe
      type: object
      x-examples: {}
      description: A recipe is a basic collection of ingredients to be prepared as a meal.
      properties:
        id:
          type: string
        name:
          type: string
        yield:
          type: string
      required:
        - id
    Ingredient:
      title: Ingredient
      type: object
      description: Ingredient is a loosely define component of a recipe that will serve to define a shopping list.
      properties:
        id:
          type: string
        name:
          type: string
        amount:
          type: string
    Meal:
      title: Meal
      type: object
      description: A meal is reference to one or more recipes selected to be made on a specific date.
      properties:
        id:
          type: string
        makeOn:
          type: number
    ShoppingList:
      title: ShoppingList
      type: object
      description: Collection of ingredients contained within a collection of meals.
      properties:
        id:
          type: string
        fromDate:
          type: number
        toDate:
          type: number
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
tags:
  - name: recipes
